[package]
name = "bento_tool_rag"
version.workspace = true
edition.workspace = true
license.workspace = true
license-file.workspace = true
readme.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
bento_protocol = { path = "../protocol" }
serde = "1.0.229"
async-trait = "0.1.92"