[package]
name = "bento_core"
version.workspace = true
edition.workspace = true
license.workspace = true
license-file.workspace = true
readme.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
async-trait = "0.1.92"
bento_host_server = { path = "../host_server" }
bento_agent_server = { path = "../agent_server" }
bento_protocol = { path = "../protocol" }
bento_tool_rag = { path = "../tool_rag" }
bento_utility = { path = "../utility" }
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
fastembed = "6.0.2"
tokio = { version = "1.53.1", features = ["macros"] }