[package]
name = "bento_core"
version.workspace = true
edition.workspace = true
license.workspace = true
license-file.workspace = true
readme.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
bento_host_server = { path = "../host_server" }
bento_agent_server = { path = "../agent_server" }
bento_tool_rag = { path = "../tool_rag" }
serde = { version = "1.0.229", features = ["derive"] }
