[package]
name = "bento_agent_server"
version.workspace = true
edition.workspace = true
license.workspace = true
license-file.workspace = true
readme.workspace = true
authors.workspace = true
description.workspace = true
repository.workspace = true

[dependencies]
bento_protocol = {path = "../protocol"}
async-trait = "0.1.92"
serde = { version = "1.0.229", features = ["derive"] }
serde_json = "1.0.151"
rmcp = { version = "3.1.4", features = ["server", "transport-streamable-http-server"] }
tokio = { version = "1.53.1", features = ["net"] }
tokio-util = "0.7.19"
axum = "0.8.9"